name: General CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - dev


jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install deps
        run: pip install pre-commit

      - name: Run linters
        run: pre-commit run --all-files


  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure poetry to not use venvs (optional)
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run pytest
        run: poetry run pytest --tb=short -q
